client/src/components/App.jsx
client/src/components/review/ReviewMain.jsx

Created the review folder under the components folder
Created ReviewMain.jsx to build out the structure if the review module;
Rendered the ReviewMain.jsx to App.jsx

Added Review Module

---

client/src/components/questions/Answer.jsx
client/src/components/questions/QuestionItem.jsx
client/src/components/questions/QuestionList.jsx

I have completed the sorting the questions and answers and the basic setting for questionsList .

Questions list

---

client/dist/index.html
package.json

- Updated package.json:
```
"react": "^16.8", 
"react-dom": "^16.8",
```
- `Deleted` the script line that adds Fontawesome since we now have React-Icons installed.
```
<script src="https://kit.fontawesome.com/89c87e5b5d.js" crossorigin="anonymous"></script>
```
link to Trello Ticket:
https://trello.com/c/SlunsmoV

React version update

---

client/src/components/review/addreview/AddReview.jsx
client/src/components/review/addreview/UploadPic.jsx
client/src/components/review/reviewmain/RatingBreakdown.jsx
client/src/components/review/reviewmain/Reviews.jsx
client/src/components/review/reviewmain/ReviewsList.jsx
client/src/components/review/reviewmain/StarRating.jsx
client/src/components/review/reviewtile/ReviewTile.jsx

- Main layout of Review Module: 
- Main layout of AddNewReview component:

Finished the layout of Review Module

---

client/src/components/questions/QuestionList.jsx
client/src/components/questions/Search.jsx

I built the search function
1. when user type more than 3 characters, the search will start filtering questions 
2. when user clear the search, it will go back to questions list
3. if no question matches it will show no questions, and ask user to add questions
@xleeocean @chiaolinghong3d

completed search

---

client/src/components/questions/Answer.jsx
client/src/components/questions/QuestionItem.jsx
client/src/components/questions/QuestionList.jsx
client/src/components/questions/Search.jsx

More question

---

client/src/components/review/addreview/AddReview.jsx
client/src/components/review/reviewmain/Reviews.jsx

Changed the AddReview component as a popup modal

---

client/src/components/App.jsx

- Added url to App.jsx
- Commented out Overview calls on state that I have not set yet.

Updated App.jsx

---

client/dist/style.css
client/src/components/App.jsx
client/src/components/overview/Overview.jsx
client/src/components/overview/OverviewStyle.jsx
client/src/components/related_products/RelatedProducts.jsx
client/src/components/related_products/RelatedProductsItem.jsx
planning-CL.md
server/routes/products.js
server/routes/questions.js

- useEffect for axios call
- added a conditional statement for render so it will only render once the data have received AND the state has been set to the new data.
.

Api connection

---

.eslintrc.js
client/src/components/review/ReviewProvider.jsx
client/src/components/review/reviewmain/RatingBreakdown.jsx
client/src/components/review/reviewmain/ReviewMain.jsx
client/src/components/review/reviewmain/Reviews.jsx
client/src/components/review/reviewmain/ReviewsList.jsx
client/src/components/review/reviewmain/StarRating.jsx
client/src/components/review/reviewmain/StarRatingInput.jsx
client/src/components/review/reviewtile/ReviewTile.jsx

Render data to reviewList

---

client/src/components/App.jsx
client/src/components/overview/Overview.jsx
client/src/components/overview/OverviewStyle.jsx
client/src/components/questions/AddQuestionModal.jsx
client/src/components/questions/Error.jsx
client/src/components/questions/QuestionList.jsx

I have completed the setup for Question modal as shown in the Checkin

Question modal

---

client/src/components/questions/AddAnswerModal.jsx
client/src/components/questions/QuestionItem.jsx
client/src/components/questions/QuestionList.jsx

This PR includes the answer modal functionality:
1. click add answer button will open the modal 
2. will throw error if required fields are not filled 
3. able to upload file 
Please see the demo

Answer modal

---

client/dist/style.css
client/src/components/overview/Overview.jsx
client/src/components/overview/OverviewStyle.jsx

- Connected to API, renders each style into an OverViewStyle component that renders a style image button
- When the style button is clicked, it will change the current style.
- Used css grid (`grid-template-areas` , `grid-template-rows: auto`, `grid-template-columns: 60% 40%`) for the Gllery and product details section.

Api Connection - Overview

---

client/src/components/App.jsx
client/src/components/review/reviewmain/ReviewMain.jsx
client/src/components/review/reviewmain/Reviews.jsx
client/src/components/review/reviewmain/ReviewsList.jsx
client/src/components/review/reviewtile/ReviewTile.jsx

Fetch data from the API

---

client/src/components/App.jsx
client/src/components/overview/Overview.jsx
client/src/components/related_products/RelatedProducts.jsx
client/src/components/related_products/RelatedProductsItem.jsx
client/src/components/related_products/YourOutfit.jsx
client/src/components/related_products/YourOutfitItem.jsx
client/src/components/related_products/YourOutfitItemCard.jsx
client/src/components/related_products/YourOutfitItemDefault.jsx
planning-CL.md

- Used localStorage to save the outfits data so that even after re-fresh, the outfits list will persist.
- Updated App.jsx so now it fetches the data from API
- When a product card is clicked, the current product will change to the clicked product -> everything will be re-rendered accordingly.
- renders the saved outfits data OR a default card if empty

Persist outfit list

---

client/dist/style.css
client/src/components/App.jsx
client/src/components/related_products/ProductComparisonModal.jsx
client/src/components/related_products/RelatedProducts.jsx
client/src/components/related_products/RelatedProductsItem.jsx

- Added a modal popup, that will be toggled on/off when you click the "info" button on the top right corner of related product cards.

Comparison Modal

---

client/src/components/questions/AddAnswerModal.jsx
client/src/components/questions/AddQuestionModal.jsx
client/src/components/questions/Answer.jsx
client/src/components/questions/QuestionItem.jsx
client/src/components/questions/QuestionList.jsx
server/routes/questions.js

I fixed the image upload feature in the add answer modal. 
It will show the preview once you select an image to upload

Upload img

---

client/dist/style.css
client/src/components/review/addreview/AddReview.jsx

- Fixed css so the popup can stay in the center of the page
- Fixed some other small problems like the star's z-index

UI improvement

---

client/dist/style.css
client/src/components/App.jsx
client/src/components/overview/Overview.jsx
client/src/components/related_products/RelatedProducts.jsx
client/src/components/related_products/RelatedProductsItem.jsx
client/src/components/related_products/YourOutfit.jsx
client/src/components/related_products/YourOutfitItem.jsx

- Added a loading icon that will run while fetching the image in Overview.
- Removed all the "isLoading..." texts
- Added the avg review number used to calculate the Star Rating for bug fix purposes.

Loading Update

---

client/src/components/questions/AddAnswerModal.jsx
client/src/components/questions/AddQuestionModal.jsx
client/src/components/questions/QuestionItem.jsx

This PR applies small UI changes. 
also, the answer modal are able to handle multiple images uploads

Css setup for QA 

---

client/dist/style.css
client/src/components/App.jsx
client/src/components/review/reviewmain/ProgressBar.jsx
client/src/components/review/reviewmain/ReviewLeft.jsx
client/src/components/review/reviewmain/ReviewMain.jsx
client/src/components/review/reviewtile/ReviewTile.jsx

Changed the dark mode and apply it to body

---

client/dist/index.html
client/dist/style.css
client/src/components/App.jsx
client/src/components/TrackerHOC/Track.js
client/src/components/TrackerHOC/Wrapper.js
client/src/components/overview/Overview.jsx
client/src/components/questions/QuestionList.jsx
client/src/components/related_products/RelatedProducts.jsx
client/src/components/related_products/RelatedProductsItem.jsx
client/src/components/related_products/YourOutfitItem.jsx
client/src/components/review/reviewmain/ReviewLeft.jsx
client/src/components/review/reviewmain/ReviewsRight.jsx

- removed all url for axios requests, so that it will no longer throw an error on AWS.
- Now the app works on AWS :)

Removed url for all API requests

---

client/src/components/review/addreview/AddReview.jsx
client/src/components/review/reviewtile/ReviewTile.jsx

- Change on the photo upload functionality to allow upload up to five photos
- Fix bug of adding new reviews
- Change the display of warning to make it more obvious
- Change the formate of time display

Review debug

---

client/dist/style.css
client/src/components/overview/Overview.jsx
client/src/components/questions/QuestionList.jsx
client/src/components/related_products/RelatedProductsItem.jsx
client/src/components/related_products/YourOutfitItem.jsx
client/src/components/related_products/YourOutfitItemDefault.jsx
client/src/components/review/reviewmain/ProgressBar.jsx
client/src/components/review/reviewmain/ReviewsRight.jsx
client/src/components/review/reviewmain/ScaleBar.jsx
client/src/components/review/reviewtile/ReviewTile.jsx

Minor adjustment on UI:
- Change color of some elements
- Add divider for questions
- Adjust size of button and remove border

UI adjustment
